#!/bin/sh

# Open specific pages on GitHub.
# See defunkt/hub for a lot more.
#
# Usage:
#
#   $ gh [repo | <treeish> | username/repo]
#
#   $ gh                  # open current repo
#   $ gh <treeish>        # open current repo @ <treeish>
#   $ gh repo             # open current user's repo
#   $ gh username/repo    # open username's repo

set -e

GITHUB="https://github.com"

case "$1" in

  */*)
    # username / repo
    open "$GITHUB/$1"
    ;;

  "")
    # current repo
    remote_username_repo=$(git config --get remote.origin.url | cut -d : -f 2 | cut -d  . -f 1)
    open "$GITHUB/$remote_username_repo"
    ;;

  *)
    # current repo @ treeish
    if git branch -a --contains "$1" &> /dev/null; then
      remote_username_repo=$(git config --get remote.origin.url | cut -d : -f 2 | cut -d  . -f 1)
      open "$GITHUB/$remote_username_repo/commit/$1"
    # current user's repo
    else
      username=$(git config --get github.user)
      open "$GITHUB/$username/$1"
    fi
    ;;

esac
