#!/usr/bin/env bash
#
# DESCRIPTION
#
#     Shows commits surrounding a given commit.
#
# USAGE
#
#     git-surround [-<n>] <commit>
#
# OPTIONS
#
#    -<n>
#        Limits the number of commits to show on either side.
#        Defaults to 5.

set -e

[ -z $1 ] && {
  echo "usage: git-surround [-<n>] <commit>" >&2
  exit 1
}

if [ $# -eq 2 ]; then
  N=${1:1}
  SHA=$2
else
  N=5
  SHA=$1
fi

git-rev-parse --verify $SHA >/dev/null 2>&1 || {
  echo "no such commit: $SHA" >&2
  exit 1
}

git log $SHA~$(($N+1))..HEAD | tail -$((2*$N+1)) && echo
