#!/usr/bin/env bash
#
# Prints your internal and/or external IP addresses.
#
# Usage:
#
#     $ ip
#     External: 123.456.78.123
#     Internal: 192.168.88.252
#
#     $ ip -i
#     192.168.88.252
#
#     $ ip -e
#     123.456.78.123
#

internal() {
  ip=$(ifconfig |
    grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' |
    grep -Eo '([0-9]*\.){3}[0-9]*' |
    grep -v '127.0.0.1')
  echo Internal: $ip
}

external() {
  ip=$(curl --silent ipinfo.io/ip)
  echo External: $ip
}

case "$1" in
  -i|--internal|in*)
    internal
    ;;

  -e|--external|ex*)
    external
    ;;

  *)
    internal
    external
    ;;
esac
