#!/usr/bin/env ruby
#
# Prints your internal and/or external IP addresses.
#
# Usage:
#
#     $ ip
#     Internal: 192.168.88.252
#     External: 123.456.78.123
#
#     $ ip -i
#     192.168.88.252
#
#     $ ip -e
#     123.456.78.123
#

def internal_ip
  # http://coderrr.wordpress.com/2008/05/28/get-your-local-ip-address
  require 'socket'
  original, Socket.do_not_reverse_lookup = Socket.do_not_reverse_lookup, true  # turn off reverse DNS resolution
  UDPSocket.open { |s| s.connect('64.233.187.99', 1); s.addr.last }
ensure
  Socket.do_not_reverse_lookup = original
end

def external_ip
  `curl --silent http://checkip.dyndns.com | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}'`
end

case ARGV[0]
when nil
  puts "Internal: #{internal_ip}"
  puts "External: #{external_ip}"
when '-i', '--internal'
  puts internal_ip
when '-e', '--external'
  puts external_ip
end
