#!/bin/bash

while x=1; do
  /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I |
    grep CtlRSSI |
    sed -e 's/^.*://g' |
    xargs -I SIGNAL printf "\rsignal: SIGNAL dBm"
  sleep 0.5
done
